halalpal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path( 'admin/', admin.site.urls),
    path('', include('system.urls')),
]

system/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from . import views

app_name = 'system'

urlpatterns = [
    path( '', views.blank, name='blank' ),

    # register pages
    url(r'^register/$', views.register, name='register'),
    #url( r'^register/$', views.UserFormView.as_view(), name='register'),

    # Login Page
    url(r'^login/$', views.login_user, name='login_user'),

    # Logout Page
	url(r'^logout/$', views.logout_user, name='logout_user'),

    # index page refer to the main page
    path('home',views.home, name='home'),

    url( r'^search/$', views.search, name="search" ),

    # Detail views
    url( r'^shop/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # write a reviews
    #url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^shop/(?P<pk>[0-9]+)/review/$', views.add_review, name="add_review"),

    # favourite a shops
    #url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^shop/(?P<pk>[0-9]+)/favourite/$', views.favourite, name="favourite"),

    path('createpoll',views.createpoll, name='createpoll'),

    path('managepoll',views.managepoll, name='managepoll'),

    url(r'^favourite/$',views.userfavourite, name='userfavourite'),

    url( r'^searchpoll/$', views.search_poll, name="search_poll" ),

    url( r'^submitpoll/$', views.submitpoll, name="submitpoll" ),

    url( r'^closepoll/$', views.closepoll, name="closepoll" ),

    url(r'^finishpoll/$', views.finishpoll, name='finishpoll'),

    url(r'^deletepoll/$', views.deletepoll, name='deletepoll'),

    # Detail views for poll
    url( r'^poll/(?P<code>[0-9]+)/$', views.poll_detail, name='poll_detail'),
]

system/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericRelation
from django.conf import settings
from django.contrib.auth.models import User
from datetime import datetime, timedelta

class Activity(models.Model):
    FAVORITE = 'F'
    ACTIVITY_TYPES = (
        (FAVORITE, 'Favorite'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    activity_type = models.CharField(max_length=1, choices=ACTIVITY_TYPES)
    date = models.DateTimeField(auto_now_add=True)

    # Below the mandatory fields for generic relation
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey()

    def __str__( self ):
        return 'Activity: %s, %s' % (self.user, self.activity_type)

# Create your models here.
class Shops( models.Model ):
    company_name = models.CharField(max_length=1000)
    address = models.CharField(max_length=1024)
    location = models.CharField(max_length=1024)
    postal_code = models.CharField(max_length=10)
    website = models.CharField(max_length=1000)
    facebook = models.CharField(max_length=1000)
    instagram = models.CharField(max_length=1000)
    phone_number = models.CharField(max_length=1000)
    email = models.CharField(max_length=1000)
    number_of_people_rated = models.IntegerField(default =0)
    categorization = models.CharField(max_length=256, default="others")
    region = models.CharField( max_length=128, default="")
    current_rating = models.IntegerField(default =0)
    #user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    favourite = GenericRelation(Activity, related_query_name='shops')

    def get_absolute_url(self):
        return reverse( 'system:detail', kwargs={'pk': self.pk} )

    def __str__( self ):
        return 'Company Name: %s, %s - %s' % (self.pk, self.company_name, self.address)

class Review( models.Model ):
    shop = models.ForeignKey( Shops, related_name="reviews_set", on_delete=models.CASCADE )
    user = models.CharField(max_length=250)
    body = models.TextField(default = "")
    rating = models.IntegerField(default = 5)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user

    def numberOfRating(self):
        return range(self.rating)

class Poll(models.Model):
    title = models.CharField(max_length=200, default='')
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    expiry_date = models.DateTimeField(default=datetime.now())
    no_of_participant = models.IntegerField(default=2)
    current_participant = models.IntegerField(default=0)
    code = models.CharField(max_length=200)
    closed = models.BooleanField(default=False)
    deleted = models.BooleanField(default=False)

    def get_absolute_url(self):
        #return "/poll/%s" %(self.code)
        return reverse( 'system:poll_detail', kwargs={'code': self.code} )

class Choice(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE )
    shop = models.ForeignKey(Shops, on_delete=models.CASCADE )
    vote_count = models.IntegerField(default=0)

class Vote(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE )
    selected = models.ForeignKey(Choice, on_delete=models.CASCADE )
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True )

system/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Review


RATING_LEVEL = (
    (1,'Rating 1'),
    (2,'Rating 2'),
    (3,'Rating 3'),
    (4,'Rating 4'),
    (5,'Rating 5'),
)

class ReviewForm( forms.ModelForm ):
    body = forms.CharField(required=True, widget=forms.Textarea(attrs={'rows': 2, 'cols': 40}))
    rating = forms.ChoiceField(  required = True, choices = RATING_LEVEL )

    class Meta:
        model = Review
        fields = [ 'body', 'rating']


class UserCreateForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

system/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Shops, Review, Activity, Poll, Choice, Vote
from .forms import ReviewForm, UserCreateForm
# for render_to_response
from django.shortcuts import render_to_response
from django.views import generic

# For login in user
from django.contrib.auth import login, logout
# login and registration form creation
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from django.contrib.contenttypes.models import ContentType

from datetime import datetime, timedelta, timezone
from django.urls import reverse
from django.http import JsonResponse
import pytz

import json
#from django.core import serializers

# Create your views here.
def blank(request):
    shops = None
    json_shops = json.dumps(shops)
    if request.method == 'GET':
        search_text = request.GET.get('search')
        #print("Search Text: " + str(search_text) )
        if search_text != None:
            sort_by = request.GET.get('sort_by')
            shops = Shops.objects.filter(company_name__contains=search_text).order_by("company_name").values_list('pk', flat=True)
            search_count = Shops.objects.filter(company_name__contains=search_text).order_by("company_name").count();
            shops = list(shops)
            json_shops = json.dumps(shops)
            #print( "Shops from home" + str(shops) )
            #serialized_shops = serializers.serialize('json', shops)
        else:
            search_text = "";
            search_count = 0;
    else:
        search_text = "";
        search_count = 0;


    # some data we might wanna pass over
    form = AuthenticationForm()
    #else redirect to login page
    if request.user.is_authenticated:
        user = request.user
        activity = Activity.objects.filter(user=user)
        context = {'form': form, 'activity':activity, 'shops': json_shops, "search_text": search_text, "search_count": search_count }
    else:
        context = {'form': form, 'shops': json_shops, "search_text": search_text, "search_count": search_count  }
    # context = {
    #     'username': request.user.get_username,
    #     'all_reports': Shops.objects.all()
    # }

    return render(request, 'system/index.html', context)
    #return redirect('system:home')
    #return HttpResponse('Hello World')

def userfavourite (request):
    # some data we might wanna pass over
    form = AuthenticationForm()
    #else redirect to login page
    if request.user.is_authenticated:
        user = request.user
        activity = Activity.objects.filter(user=user)
        context = {'form': form, 'activity':activity  }
    else:
        context = {'form': form }
        return redirect('system:login_user')
    # context = {
    #     'username': request.user.get_username,
    #     'all_reports': Shops.objects.all()
    # }

    return render(request, 'system/favourite.html', context)

def home(request):

    shops = None
    json_shops = json.dumps(shops)
    if request.method == 'GET':
        search_text = request.GET.get('search')
        #print("Search Text: " + str(search_text) )
        if search_text != None:
            sort_by = request.GET.get('sort_by')
            shops = Shops.objects.filter(company_name__contains=search_text).order_by("company_name").values_list('pk', flat=True)
            search_count = Shops.objects.filter(company_name__contains=search_text).order_by("company_name").count();
            shops = list(shops)
            json_shops = json.dumps(shops)
            #print( "Shops from home" + str(shops) )
            #serialized_shops = serializers.serialize('json', shops)
        else:
            search_text = "";
            search_count = 0;
    else:
        search_text = "";
        search_count = 0;


    # some data we might wanna pass over
    form = AuthenticationForm()
    #else redirect to login page
    if request.user.is_authenticated:
        user = request.user
        activity = Activity.objects.filter(user=user)
        context = {'form': form, 'activity':activity, 'shops': json_shops, "search_text": search_text, "search_count": search_count }
    else:
        context = {'form': form, 'shops': json_shops, "search_text": search_text, "search_count": search_count  }
    # context = {
    #     'username': request.user.get_username,
    #     'all_reports': Shops.objects.all()
    # }

    return render(request, 'system/home.html', context)

def createpoll(request):
    # some data we might wanna pass over
    form = AuthenticationForm()
    #else redirect to login page
    if request.user.is_authenticated:
        user = request.user
        activity = Activity.objects.filter(user=user)
        context = {'form': form, 'activity':activity }
    else:
        context = {'form': form }
        return redirect('system:login_user')
    # context = {
    #     'username': request.user.get_username,
    #     'all_reports': Shops.objects.all()
    # }

    return render(request, 'system/createpoll.html', context)

def logout_user(request):
    if request.method == 'POST':
        logout(request)
        return redirect('system:home')
        #return redirect('system:login_user')

def register(request):
    if request.user.is_authenticated:
        return redirect('system:home')
    form = AuthenticationForm()
    if request.method == 'POST':
        form_register = UserCreateForm(request.POST)
        if form_register.is_valid():
            form_register.save()
            return redirect('system:home')
    else:
        # Note: UserCreateForm is Used that is defined in form.py
        form_register = UserCreateForm()

    template_name = 'system/register.html'
    return render(request, template_name, {'form_register': form_register, 'form': form } )

def login_user(request):
    if request.user.is_authenticated:
        return redirect('system:home')
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log user in
            user = form.get_user()
            login(request, user)
            return redirect('system:home')
    else:
        form = AuthenticationForm()

    template_name = 'system/login.html'
    return render(request, template_name, {'form': form} )


def search( request ):
    if request.method == 'POST':
        #theShopsId = json.loads(request.POST.get('search_result'))
        theShopsId = request.POST.getlist('search_result[]')
        #theShopsId
        # selected_shop = Shops.objects.filter(id__in=theID)
        # #search_text = request.POST['search_text']
        sort_by = request.POST['sort_by']
        region_filtered = request.POST.getlist('region_filtered[]')
        type_filtered = request.POST.getlist('type_filtered[]')
    else:
        theShopsId = [];

    #print(search_text)

    print( "Shops ID: " + str(theShopsId) )

    # SQLITE_LIMIT_VARIABLE_NUMBER issue where SQLite will have this error "“Too many SQL variables” error in django witih sqlite3"
    # The issue SUSPECTED comes from ".filter(id__in=theShopsId).". Earlier version works fine
    # Remove this line if database is change 
    theShopsId = theShopsId[:950]

    #print("Region: " + str(region_filtered) )
    #print("Type: " + str(type_filtered) )

    search_text = "";

    #shops = Shops.objects.filter(company_name__contains=search_text)
    if( sort_by == "alphabeticalAZ" ):
        #shops = Shops.objects.filter(region__in=region_filtered).filter(categorization__in=type_filtered).filter(company_name__contains=search_text).order_by("company_name")
        shops = Shops.objects.filter(region__in=region_filtered).filter(categorization__in=type_filtered).filter(id__in=theShopsId).order_by("company_name")
        #shops = Shops.objects.filter(region__in=region_filtered).filter(categorization__in=type_filtered).filter(company_name__contains=search_text).order_by("company_name")
    elif( sort_by == "alphabeticalZA" ):
        #shops = Shops.objects.filter(region__in=region_filtered).filter(categorization__in=type_filtered).filter(company_name__contains=search_text).order_by("-company_name")
        shops = Shops.objects.filter(region__in=region_filtered).filter(categorization__in=type_filtered).filter(id__in=theShopsId).order_by("-company_name")
    elif( sort_by == "popularity" ):
        #shops = Shops.objects.filter(region__in=region_filtered).filter(categorization__in=type_filtered).filter(company_name__contains=search_text).order_by("-current_rating")
        shops = Shops.objects.filter(region__in=region_filtered).filter(categorization__in=type_filtered).filter(id__in=theShopsId).order_by("-current_rating")
    else:
        #shops = Shops.objects.filter(region__in=region_filtered).filter(categorization__in=type_filtered).filter(company_name__contains=search_text)
        shops = Shops.objects.filter(region__in=region_filtered).filter(categorization__in=type_filtered).filter(id__in=theShopsId)


    #print( "Shop Count: " + str(shops) )

    return render_to_response("ajax_search.html", {'shops': shops } )

def search_poll( request ):
    if request.method == 'POST':
        search_text = request.POST['search_text']
    else:
        search_text = "";

    print(search_text)

    shops = Shops.objects.filter(company_name__contains=search_text)

    return render_to_response("ajax_poll.html", {'shops': shops } )

def add_review( request, pk ):
    shop = get_object_or_404( Shops, pk=pk )
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.shop = shop

system/templates/system/add_review.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<!-- Bootstrap core JavaScript-->
<!-- <script src="{%  static 'vendor/jquery/jquery.min.js' %}"></script> -->
<!-- Core plugin JavaScript-->
<!-- <script src="{%  static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script> -->
<!-- Stylesheet -->
<link href="{%  static 'css/stylesheet.css' %}" rel="stylesheet">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<link href="https://fonts.googleapis.com/css?family=Open+Sans:600" rel="stylesheet">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/i18n/defaults-en_US.js"></script>


<script>
	$( function() {
		$('#search').keyup( function()  {
			console.log("Hello");
			$.ajax( {
				type: 'POST',
				url: '/search/',
				data: {
					'search_text': $('#search').val(),
					'csrfmiddlewaretoken' : $("input[name=csrfmiddlewaretoken]").val()
				},
				success: searchSuccess,
				dataType: 'html'
			} );
		} );

	});

	function searchSuccess(data, textStatus, jqXHR ) {
		console.log("Success")
		$('#search-results').html(data);
	}

	$(window).on('load', function() {
    console.log( "ready!" );
		// Get the modal
		var modal = document.getElementById('id01');

		// When the user clicks anywhere outside of the modal, close it
		window.onclick = function(event) {
		    if (event.target == modal) {
		        modal.style.display = "none";
		    }
		}
	});

</script>
<style>
.result-container {
	margin: 20px auto;
	box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
  width: 50%;
  padding: 10px;
	text-align: center;
}

/* Add padding to containers */
.container {
    padding: 16px;
    background-color: white;
}

/* Full-width input fields */
input[type=text], input[type=password] {
    width: 100%;
    padding: 15px;
    margin: 5px 0 22px 0;
    display: inline-block;
    border: none;
    background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
    background-color: #ddd;
    outline: none;
}

/* Overwrite default styles of hr */
hr {
    border: 1px solid #f1f1f1;
    margin-bottom: 25px;
}

/* Set a style for the submit button */
.registerbtn {
    /* background-color: #4CAF50; */
		background-color: #c0392b;
    color: white;
    padding: 16px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
    opacity: 0.9;
}

.registerbtn:hover {
    opacity: 1;
}

/* Add a blue text color to links */
a {
    color: dodgerblue;
}

/* Set a grey background color and center the text of the "sign in" section */
.signin {
    background-color: #f1f1f1;
    text-align: center;
}

textarea {
    width: 100%;
    height: 150px;
    padding: 12px 20px;
    box-sizing: border-box;
    border: 2px solid #ccc;
    border-radius: 4px;
    background-color: #f8f8f8;
    font-size: 16px;
    resize: none;
		margin-bottom: 20px;
}

.navbar-header{
  margin-left:5px;
  width:100%;
}

.container {
	padding: 16px;
	background-color: white;
	width: 100%;
}

.footer {
    padding: 20px;
    text-align: center;
    background: #444;
    color: #fff;
    /* margin-top: 20px; */
		position: fixed;
    left: 0;
    bottom: 0;
		width: 100%;
}
a:hover, a:visited, a:link, a:active {
    text-decoration: none;
		color: #555;
}

</style>
</head>
<body>

	<!-- navbar-dark bg-info -->
	<nav class="navbar navbar-expand-sm" style="padding: 10px 15%;">
	<div class="navbar-header">
	    <a class="navbar-brand" href="{% url 'system:blank'%}"><img src="{% static 'image/logo.png' %}" alt="banner" class="responsive" style="height: 60px; width: 120px; margin-top: -10px;"></a>

	    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsingNavbarXs">
	        <span class="navbar-toggler-icon"></span>
	    </button>
	    <div class="navbar-collapse collapse pull-right" id="collapsingNavbarXs">
	        <ul class="navbar-nav" style="font-family: 'Open Sans'; font-size: 18px; color: black;">
							{% if user.is_authenticated %}
	            <li class="nav-item">
	                <a class="nav-link" href="{% url 'system:createpoll'%}">Create Poll</a>
	            </li>
	            <li class="nav-item">
	                <a class="nav-link" href="{% url 'system:managepoll'%}">Manage Poll</a>
	            </li>
	            <li class="nav-item">
	                <a class="nav-link" href="{% url 'system:userfavourite'%}">Favourites</a>
	            </li>
							{% endif %}
							<li class="nav-item">
									{% if user.is_authenticated %}
									{% else %}
											<a class="nav-link" href="{% url 'system:register'%}">Register</a>
									{% endif %}
	            </li>
	            <li class="nav-item">
									<!--
										For UNAUTHENTICATED user calling {{user.is_authenticated}} results:
											CallableBool(True) (when on Django < 1.10 it was True)
										For AUTHENTICATED user calling {{user.is_authenticated}} results:
											CallableBool(False) (when on Django < 1.10 it was False)
									-->
									{% if user.is_authenticated %}
										<form id="logout-form" action="{% url 'system:logout_user'%}" method='POST'>
											{% csrf_token %}
											<!-- <button type="submit" class="auth_btn" style="width:auto;">Logout</button> -->
										</form>
										<!-- Note: This is outside the form as to align with other on the nav bar list -->
										<a class="nav-link" href="javascript:{}" onclick="document.getElementById('logout-form').submit(); return false;">Logout</a>
									{% else %}
									  	<a class="nav-link" onclick="document.getElementById('id01').style.display='block'"  href="#">Login</a>
											<!-- <button class="auth_btn" onclick="document.getElementById('id01').style.display='block'" style="width:auto;">Login</button> -->
									{% endif %}
	            </li>
	        </ul>
	    </div>
	</div>
	</nav>
<div class="result-container">
		<form action="" method="POST">
			<div class="container">
				<h1>Add Review</h1>
				<p>Please fill in this form to review of the shop</p>
				{% csrf_token %}
				{{ form.as_p }}
				<button type="submit" class="registerbtn">Post Review</button>
				</div>
		</form>
</div>

</body>
</html>

system/templates/system/login.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<!-- Bootstrap core JavaScript-->
<script src="{%  static 'vendor/jquery/jquery.min.js' %}"></script>
<!-- Core plugin JavaScript-->
<script src="{%  static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
<!-- Stylesheet -->
<link href="{%  static 'css/stylesheet.css' %}" rel="stylesheet">

<script>
	$( function() {
		$('#search').keyup( function()  {
			console.log("Hello");
			$.ajax( {
				type: 'POST',
				url: '/search/',
				data: {
					'search_text': $('#search').val(),
					'csrfmiddlewaretoken' : $("input[name=csrfmiddlewaretoken]").val()
				},
				success: searchSuccess,
				dataType: 'html'
			} );
		} );

	});

	function searchSuccess(data, textStatus, jqXHR ) {
		console.log("Success")
		$('#search-results').html(data);
	}

	$(window).on('load', function() {
    console.log( "ready!" );
		// Get the modal
		var modal = document.getElementById('id01');

		// When the user clicks anywhere outside of the modal, close it
		window.onclick = function(event) {
		    if (event.target == modal) {
		        modal.style.display = "none";
		    }
		}
	});

</script>
<style>
.result-container {
	margin: 20px auto;
	box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
  width: 50%;
  padding: 10px;
	text-align: center;
}

/* Add padding to containers */
.container {
    padding: 16px;
    background-color: white;
}

/* Full-width input fields */
input[type=text], input[type=password] {
    width: 100%;
    padding: 15px;
    margin: 5px 0 22px 0;
    display: inline-block;
    border: none;
    background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
    background-color: #ddd;
    outline: none;
}

/* Overwrite default styles of hr */
hr {
    border: 1px solid #f1f1f1;
    margin-bottom: 25px;
}

/* Set a style for the submit button */
.registerbtn {
    background-color: #4CAF50;
    color: white;
    padding: 16px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
    opacity: 0.9;
}

.registerbtn:hover {
    opacity: 1;
}

/* Add a blue text color to links */
a {
    color: dodgerblue;
}

/* Set a grey background color and center the text of the "sign in" section */
.signin {
    background-color: #f1f1f1;
    text-align: center;
}

</style>
</head>
<body>

<div class="topnav">
  <a class="active" href="{% url 'system:home'%}">Home</a>
	{% if user.is_authenticated %}
		<a href="{% url 'system:userfavourite'%}">Favourite</a>
		<a href="{% url 'system:managepoll'%}">Manage Poll</a>
		<a href="{% url 'system:createpoll'%}">Create Poll</a>
	{% endif %}
</div>

<div class="result-container">
		<form action="{% url 'system:login_user' %}" method="POST">
			<div class="container">
				<h1>Login</h1>
				<p>Please fill in this form to login.</p>
				{% csrf_token %}
				{{ form }}
				<button type="submit" class="registerbtn">Login</button>
				</div>

				<div class="container signin">
				<p>New user? <a href="{% url 'system:register'%}">Register</a>.</p>
			</div>
		</form>
</div>

</body>
</html>